### ISSUE TITLE
db-migrate up doesn't seem to handle coffeescript on Heroku

### ISSUE THREAD

**Issue by pawelkomarnicki** [kunklejr/node-db-migrate#148] opened 2014-02-05 17:11 UTC
I get following error (breaks on coffeescript-based syntax)
```
heroku run db-migrate up
Running `db-migrate up` attached to terminal... up, run.6865

/app/migrations/20140130094543-add-accounts.coffee:6
# Create accounts table with fields:
^
[ERROR] SyntaxError: Unexpected token ILLEGAL
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at [object Object].Migration._up (/app/node_modules/db-migrate/lib/migration.js:90:10)
  at [object Object].Migration.up (/app/node_modules/db-migrate/lib/migration.js:102:8)
  at Object.Migrator.up (/app/node_modules/db-migrate/lib/migrator.js:87:7)
  at /app/node_modules/db-migrate/lib/migrator.js:127:18
  at [object Object].callback (/app/node_modules/db-migrate/lib/driver/pg.js:16:44)
  at [object Object].Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:84:10)
  at [object Object].<anonymous> (/app/node_modules/pg/lib/client.js:159:19)
  at [object Object].EventEmitter.emit (events.js:117:20)
  at [object Object].<anonymous> (/app/node_modules/pg/lib/connection.js:97:12)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

Any suggestions how to get it fixed? :) Thanks

**Comment by wzrdtales** [comment] 2015-02-26 20:13
Can't reproduce

I close this as very old and we may talk about very old versions. If this problem is still existent, please reopen this issue and post new logs and I will try to get this fixed.

**Closed by wzrdtales** 2015-02-26 20:13 UTC
Labels: needs confirmation, question
