### ISSUE TITLE
Migrating up and down throw an Error

### ISSUE THREAD

**Issue by alexhanh** [kunklejr/node-db-migrate#139] opened 2013-11-26 00:26 UTC
```
Alexanders-MacBook-Air:nodetest alexanderhanhikoski$ ./node_modules/db-migrate/bin/db-migrate up
[INFO] Processed migration 20131126000219-AddTables
[INFO] Processed migration 20131126000219-AddTables
[INFO] Processed migration 20131126000219-AddTables
[INFO] Processed migration 20131126000219-AddTables
[INFO] Done
[ERROR] TypeError: Cannot read property 'name' of undefined
    at /Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/db-migrate/lib/migrator.js:125:66
    at iterate (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/db-migrate/node_modules/async/lib/async.js:108:13)
    at /Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/db-migrate/node_modules/async/lib/async.js:119:25
    at null.callback (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/db-migrate/lib/driver/pg.js:20:43)
    at Query.handleReadyForQuery (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/pg/lib/query.js:84:10)
    at null.<anonymous> (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/pg/lib/client.js:148:19)
    at EventEmitter.emit (events.js:117:20)
    at null.<anonymous> (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/pg/lib/connection.js:97:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
Alexanders-MacBook-Air:nodetest alexanderhanhikoski$ ./node_modules/db-migrate/bin/db-migrate down
[INFO] Processed migration 20131126000219-AddTables
[INFO] Done
[ERROR] TypeError: Cannot call method 'sync' of undefined
    at Query.handleError (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/pg/lib/query.js:92:16)
    at null.<anonymous> (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/pg/lib/client.js:167:24)
    at g (events.js:175:14)
    at EventEmitter.emit (events.js:92:17)
    at Socket.<anonymous> (/Users/alexanderhanhikoski/Code/batrix/batrix-backend/nodetest/node_modules/pg/lib/connection.js:60:10)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

The migrations where persisted as I see the tables in the database. The migration simply contains 4 runSql commands. Interestingly enough, when I run only a single runSql command, it completes without errors.

**Comment by wzrdtales** [comment] 2015-02-26 20:28
Seems to be fixed in the newest, can't reproduce this.

Feel free to reopen if this error still occurs and post a log and details about your used migrations and setup

**Closed by wzrdtales** 2015-02-26 20:28 UTC
